### ISSUE TITLE
Add project notice to geogeeks website

### ISSUE THREAD

**Issue by samwilson** [geogeeks-au/MainRoads-to-OSM#8]

**Comment by johnwbryant** [comment]
Done. Added this project to website and Frisson, GeoMediaStatements too. Looks much more respectable!

**Comment by samwilson** [comment]
Thanks John!

**Comment by johnwbryant** [comment]
No problem! Keith set up a nifty thing where the github issues that have a label get pulled into the website... so if we add labels to the issues they'll automatically show up there. Cool!

**Comment by samwilson** [comment]
Oh that's very cool! I'd not noticed it before.

I've added http://geogeeks.org/projects/main-roads-to-osm.html as the website GH lists for this repo.
